### ISSUE TITLE
Ldap authentification

### ISSUE THREAD

**Issue by onfcharbonnier** [MercenariesEngineering/coalition#27]
Ajouter un bouton de login via Ldap pour autoriser le changement des variables d'un job (affinity, priority, user etc...)

Désactiver la possibilité de faire ces changement, la creation de jobs via l'interface et les pages  worker/affinities aux personnes non autorisées ou non loggées.

On doit pouvoir consulter et lancer des jobs via l'API sans authent.

**Comment by AlphonseAllais** [comment]
Ces fonctionnalités sont disponibles depuis la version 7cfed002f41fb20c3b473c5b76763dc73b14318a .

**Comment by hulud75** [comment]
Yep, tout est en place normalement.
