### ISSUE TITLE
quota et priorité par projet

### ISSUE THREAD

**Issue by onfcharbonnier** [MercenariesEngineering/coalition#28]
Ajouter la possibilité de lancer des jobs dans un projet et d'avoir des priorités et quota par projet

exemple:

prod1            priorite 250 quota 300 
 job0001
  frame...

prod2            priorite 250 quota 100 
 job0002
  frame...

si des machines sont dispo elle doivent pouvoir aller sur les jobs de prod1 même si le quota de 300 est atteint

**Comment by AlphonseAllais** [comment]
Les projets évoqués correspondent aux affinités liées à un job?

**Comment by hulud75** [comment]
Je confirme, il est possible maintenant de mettre différentes listes d'affinités à un worker.

Dans ton cas il suffit de mettre 300 workers avec les affinités suivantes :
prod1
prod2

Et 100 workers avec les affinités suivantes :
prod2
prod1

Cyril
